name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Other changes'
    labels:
      - 'chore'
      - 'docs'
      - 'style'
      - 'perf'
      - 'test'
  - title: 'Breaking Changes'
    labels:
      - 'chore!'
      - 'fix!'
      - 'bugfix!'
      - 'bug!'
template: |
  ## Changes

  $CHANGES
