apiVersion: v1
kind: Pod
metadata:
  name: node
spec:
  containers:
    - name: python
      image: python:3-alpine
      tty: true
      command:
        - cat
      resources:
        requests:
          memory: '512Mi'
          cpu: '1'
        limits:
          memory: '512Mi'
          cpu: '1'
    - name: docker
      image: gcr.io/kaniko-project/executor:debug
      tty: true
      command:
        - /busybox/cat
      resources:
        requests:
          memory: '256Mi'
          cpu: '100m'
        limits:
          memory: '256Mi'
          cpu: '100m'
